# Introduction to torch tensors

We start with matrices in numpy and its equivalent form in torch.

In [1]:
import numpy as np
import torch

In [2]:
# Vetores
v = [2, 3, 5] 

v_np = np.array(v)
v_torch = torch.tensor(v)

print("Lista em python: ", v)
print("Array em numpy: ", v_np)
print("Tensor torch: ", v_torch)

Lista em python:  [2, 3, 5]
Array em numpy:  [2 3 5]
Tensor torch:  tensor([2, 3, 5])


In [3]:
# Matrizes
m = [[2.0, 3.0, 5.0], [1.0, 0, 1.0]] 

m_np = np.array(m)
m_torch = torch.tensor(m)

print("Python: ", m)
print("Numpy: ", m_np)
print("Torch: ", m_torch)

Python:  [[2.0, 3.0, 5.0], [1.0, 0, 1.0]]
Numpy:  [[2. 3. 5.]
 [1. 0. 1.]]
Torch:  tensor([[2., 3., 5.],
        [1., 0., 1.]])


In [4]:
# Recuperando a dimensao do array (numpy)
print(m_np.shape)

# Recuperando a dimensao (formato) do tensor
print(m_torch.shape)

(2, 3)
torch.Size([2, 3])


In [6]:
# slicing

print(m_torch[0, 1].item())  # recupera o elemento na linha 1, coluna 2

print(m_torch[:, 0]) # recupera a primeira coluna (ou coluna 0)

print(m_torch[0, :]) # recupera a primeira linha (ou linha 0)

print(m_torch[:, 0:-1]) # = m_torch[:, 0:2]


3.0
tensor([2., 1.])
tensor([2., 3., 5.])
tensor([[2., 3.],
        [1., 0.]])


In [36]:
# Criando tensores aleatórios

m_aleatoria = torch.rand(5, 3)
print(m_aleatoria)

a_aleatoria = np.random.rand(5, 5)
print(a_aleatoria)

tensor([[0.2670, 0.3021, 0.0228],
        [0.3006, 0.2984, 0.3315],
        [0.0902, 0.4470, 0.8662],
        [0.4423, 0.3836, 0.2812],
        [0.6573, 0.9635, 0.5582]])
[[0.79236443 0.23016358 0.38599992 0.0267528  0.58905181]
 [0.51649234 0.18610819 0.22612061 0.25563832 0.75705574]
 [0.83136125 0.04152048 0.22407562 0.1199043  0.59837074]
 [0.21788849 0.19248744 0.76728772 0.68924414 0.44890463]
 [0.90827948 0.78239531 0.02865923 0.13084321 0.12799087]]


Defining common matrices/tensors

In [9]:
x = np.ones((2, 2))
y = torch.ones(2,2)

print(x)
print(y)

[[1. 1.]
 [1. 1.]]
tensor([[1., 1.],
        [1., 1.]])


In [43]:
# Trasnformando de numpy para torch

np_array = np.ones((2, 2))
print(np_array)
print(type(np_array))

tensor = torch.from_numpy(np_array)
print(tensor)

[[1. 1.]
 [1. 1.]]
<class 'numpy.ndarray'>
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [44]:
# Passando de torch para numpy

torch_tensor = torch.ones((2,2))
print(torch_tensor)
print(type(torch_tensor))

z = torch_tensor.numpy()
print(z)
print(type(z))

tensor([[1., 1.],
        [1., 1.]])
<class 'torch.Tensor'>
[[1. 1.]
 [1. 1.]]
<class 'numpy.ndarray'>


In [15]:
# Remodelando tensors

a = torch.rand(2, 4)
print(a)
print(a.shape[0])

print(a.view(2, 2, -1))  # Qual a diferença entre view e reshape (em torch)?


tensor([[0.8369, 0.5055, 0.1847, 0.4179],
        [0.0686, 0.4831, 0.2262, 0.6172]])
2
tensor([[[0.8369, 0.5055],
         [0.1847, 0.4179]],

        [[0.0686, 0.4831],
         [0.2262, 0.6172]]])


In [14]:
teste = torch.rand(2)
print(teste)
teste.view(4,-1)

tensor([0.7020, 0.0383])


RuntimeError: shape '[4, -1]' is invalid for input of size 2

In [17]:
# Apertando e afrouxando tensores

x = torch.rand(2, 3, 1, 4, 1)
print(x.shape)

x = x.unsqueeze(dim=1)
print(x.shape)

x = x.squeeze() 
print(x.shape)

torch.Size([2, 3, 1, 4, 1])
torch.Size([2, 1, 3, 1, 4, 1])
torch.Size([2, 3, 4])


In [19]:
# Element-wise addition

a = torch.Tensor([[1, 2], [3, 4]])
b = torch.ones((2,2))
c = a.view(4, -1)

a = c.view(2, 2)

print(a+b) #or
print(a.add(b))

RuntimeError: The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 0

In [86]:
a.add_(b)  # it changes the value of a (in-place addition)
#print(c)
print(a)

#the same is valid for subtraction (sub() or sub_())

tensor([[2., 3.],
        [4., 5.]])


In [89]:
# Multiplicação elemento-a-elemento

a = torch.Tensor([[1, 2], [3, 4]])
b = torch.Tensor([[4, 2], [3, 4]])

print(a)
print(b)
print(a * b)

tensor([[1., 2.],
        [3., 4.]])
tensor([[4., 2.],
        [3., 4.]])
tensor([[ 4.,  4.],
        [ 9., 16.]])


In [97]:
# Multiplicação de matrizes
A = torch.rand(2, 2)
B = torch.rand(3, 2)

print(A @ B.T) # Use .T para obter o transposto de uma matriz 


tensor([[0.2565, 0.1482, 0.1945],
        [0.4432, 0.2917, 0.4780]])


In [107]:
# Media e desvio padrao

t = torch.rand(10)
print(f"Media: {t.mean():.2f}")  # ou torch.mean(t)
print(f"Desvio Padrao: {t.std():.2f}") # ou torch.std(t)

t2 = torch.rand(10, 2)
print(t2.mean())  # media de toda a matriz

print(t2.mean(dim=0)) # media computada ao longo das linhas (dim=0)

Media: 0.50
Desvio Padrao: 0.34
tensor(0.5458)
tensor([0.5264, 0.5653])


In [22]:
m = torch.rand(3, 3)
print(m.diag().mean())

tensor(0.3451)


In [117]:
# Shape, size() e dim()

x = torch.rand(3, 10)
print(x.shape)
print(x.size())
print(x.dim())

torch.Size([3, 10])
torch.Size([3, 10])
2
