# Variables and Gradients

In [10]:
# Variables are now deprecated in Torch 0.4
# This way, there is no difference between the codes bellow

import torch
from torch.autograd import Variable

x = torch.tensor([[1,2],[3,4]], requires_grad=True)
y = Variable(torch.tensor([4,3,2,1]), requires_grad=True)

print(x)
print(x.requires_grad)
print(y)

#or 

x = torch.Tensor([1,2,3,4])
print(x)
print(x.requires_grad)
x.requires_grad_()
print(x.requires_grad)



tensor([[ 1,  2],
        [ 3,  4]])
True
tensor([ 4,  3,  2,  1])
tensor([ 1.,  2.,  3.,  4.])
False
True


In [19]:
# now let's see how autograd works.

# First, let's define our parameters (variables)

x = torch.tensor([1,2,3])
x.requires_grad_()

# our cost functions is x_1 + x_2^2 + x_3^3
o = x[0] + x[1]**2 + x[2]**3
print(o)

o.backward() #This dispatches the gradients to the computational graph

# for example, if we want to know the gradient of o wrt to x_1
x.grad



tensor(32)


tensor([  1,   4,  27])